### PR TITLE
WIP: Dockerizationing

### LINKED ISSUE #9: Dockerize all the things
As a contributor, I want a script to set up a development environment with a local Postgres database. I want it to be frictionless.

Right now, we're contacting the deployed Amazon database when talking to our local API endpoints. We should instead hit a local Postgres instance, so that we don't pollute the global database.

### PR DESCRIPTION
**Pull request by mciantyre**
We introduce Docker Compose to configure local development environments. Docker Compose allows us to define an environment with multiple containers. In our use-case, Docker compose spins up the Express backend and a Postgres database, and it links the two together. With a simple

```
$ docker-compose up
```

we're up and running. Users are free to _not_ use Docker Compose, of course. The tool simply automates the manual process of setting up an environment.

Usage requires Docker, and Docker Compose. Installation varies by system. You can learn more [here](https://docs.docker.com/install/).

TODOs:

- [ ] Get one reviewer to sign-off on ease of use
- [x] ~~spin-up the front-end. I'm only doing the API backend and the database. There should be a way to run / test the UI.~~ Don't care
- [x] your suggestions here!

Please block the PR until the first TODO is resolved. I like work-in-progress (WIP) PRs so that we can discuss the work.

Closes #9

### CODE REVIEW

**Comment by aadupirn** [comment]
I might want to merge this now just to have the entire backend containerized so I'm not messing with the production db. The client is easy to run anyway.

**Comment by mciantyre** [comment]
Does it work on your system? Is it easy enough to work with? I'm looking for some usability feedback too.

**Comment by mciantyre** [comment]
@ayeungturtle If you have time to give this a try, let me know what you think!

**Comment by ayeungturtle** [comment]
I downloaded Docker over lunch, but things got wonky somewhere in the installation.  My computer was pooped out for a good 15 minutes after lunch : /  I'll have to sort it out later and give it another shot.

**Pull request merged**
